use_frameworks!

platform :ios, '11.0'

target 'IosAnalyticsDebugger_Example' do
  pod 'IosAnalyticsDebugger', :path => '../'

  target 'IosAnalyticsDebugger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
