use_frameworks!

platform :ios, '10.0'

target 'IosAnalyticsDebugger_Example' do
  pod 'IosAnalyticsDebugger', :path => '../'

  pod 'AvoInspector', '~> 0.9.4'
  
  target 'IosAnalyticsDebugger_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
